### PR TITLE
Derive `Default` for schema ast types

### PR DESCRIPTION
**Pull request by leodasvacas**
This makes them easier to construct.

### CODE REVIEW

**Comment by tailhook** [comment]
While it gives the shortest code, is using `Default` a best way to construct these values? Especially considering that some of them are invalid when constructing default (i.e. empty name).

Maybe it's better to make a `fn new(name)` method? (except for Schema and Document)

**Comment by leodasvacas** [comment]
For my use case which are unit tests empty names work fine, the default value is not completely unusable.

**Comment by tailhook** [comment]
It would make more sense if trait would be `TestData::generate()` instead of `Default::default()`. Would `new("test_data")` be too cumbersome for you?

**Comment by leodasvacas** [comment]
That would be fine, I'll update this to add a `new(name)` instead of `Default` where that is better.

**Comment by leodasvacas** [comment]
Done, let me know what you think.

**Comment by tailhook** [comment]
Looks fine. Merged. Thanks!

**Comment by tailhook** [comment]
Released as v0.2.2

**Pull request merged**
