### PR TITLE
Add Serde Support For AST

### PR DESCRIPTION
**Pull request by anshap1719**

### CODE REVIEW

**Comment by LegNeato** [comment]
Should this support deserializing as well?

**Comment by anshap1719** [comment]
@LegNeato I now remember why I didn't add it initially. It's because of having to deal with lifetimes and I didn't want to bother with that at the time. I will eventually (hopefully soon) add it in, but just wanted to give you an update here.

**Comment by LegNeato** [comment]
@tyranron are you ok with this landing without deserialize or do you want to wait? (I haven't reviewed yet FYI)

**Comment by tyranron** [comment]
@LegNeato I think we need @tailhook's decision/opinion here as a main maintainer of this crate. I haven't actually dived into `graphql-parser`'s code yet.

**Comment by LegNeato** [comment]
Ah yeah, I was in the wrong project 🤣

**Review by LegNeato — CHANGES_REQUESTED** [review]
This looks fairly mechanical and good. Can you add a test (this could just be calling a no-op  function that has the Serialize bound) and add using / not using this flag to CI so we don't accidentally break it?

**Comment by sodiumjoe** [comment]
👋 I need both serialization and deserialization for a project I'm working on. I am willing to try to finish this PR by adding a test and also adding deserialization, but the second one might be a bit beyond my abilities.

I checked out the wip commit before the reverts of the deserialization, but haven't been able to fix the lifetime issues. If someone is willing and available to provide some guidance, I'm still happy to try to make progress on this.

The lifetime issues are pretty tricky as they seem to come from the derive macro implementation.

On [this line](https://github.com/graphql-rust/graphql-parser/pull/77/commits/0a1bb60d8d7cd52bbdf83d40cde2236d533ac4ec#diff-e24518d69b6357926bce35868225330c1992a4029b521c0112b4ec8523ddc31cR18),  the `+ Serialize + Deserialize<'a>` seem unnecessary, as the implementer of the `Text` trait should impl them if required.

When I try removing those, I get fewer (10) compiler errors, that look like this
```
help: `'de` and `'a` must be the same: replace one with the other

error: lifetime may not live long enough
  --> src/schema/ast.rs:43:25
   |
38 | #[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
   |                                                 ----------- lifetime `'de` defined here
39 | pub enum Definition<'a, T: Text<'a>> {
   |                     -- lifetime `'a` defined here
...
43 |     DirectiveDefinition(DirectiveDefinition<'a, T>),
   |                         ^^^^^^^^^^^^^^^^^^^ requires that `'de` must outlive `'a`
   |
   = help: consider adding the following bound: `'de: 'a`
```

I tried using `serde(borrow = "'a")` as described [here](https://serde.rs/lifetimes.html#borrowing-data-in-a-derived-impl), but that doesn't seem to work.

Any help appreciated!

**Comment by sodiumjoe** [comment]
I got some help from a colleague: https://github.com/graphql-rust/graphql-parser/pull/80

**Comment by anshap1719** [comment]
Thanks @sodiumjoe, I'll close this PR in favour of yours.

**Pull request closed without merging**
